"""updated db for new models: superuser and address

Revision ID: 3977aa95b1c9
Revises: fca8f62100ce
Create Date: 2021-04-19 07:50:14.305774

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3977aa95b1c9'
down_revision = 'fca8f62100ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('superusers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('firstname', sa.String(), nullable=False),
    sa.Column('lastname', sa.String(), nullable=False),
    sa.Column('phone', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('user_type', sa.Enum('doctor', 'patient', 'superuser', name='enumtype'), server_default='superuser', nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('addresss',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('zip_code', sa.String(), nullable=False),
    sa.Column('address', sa.String(), nullable=False),
    sa.Column('address_complement', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=False),
    sa.Column('state', sa.String(), nullable=False),
    sa.Column('country', sa.String(), nullable=False),
    sa.Column('episode_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['episode_id'], ['episodes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('doctors', sa.Column('user_type', sa.Enum('doctor', 'patient', 'superuser', name='enumtype'), server_default='doctor', nullable=False))
    op.add_column('patients', sa.Column('user_type', sa.Enum('doctor', 'patient', 'superuser', name='enumtype'), server_default='patient', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('patients', 'user_type')
    op.drop_column('doctors', 'user_type')
    op.drop_table('addresss')
    op.drop_table('superusers')
    # ### end Alembic commands ###
