"""column disabled

Revision ID: 89eba48f31b0
Revises: 054cee3f4d64
Create Date: 2021-04-22 10:12:55.880466

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '89eba48f31b0'
down_revision = '054cee3f4d64'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('doctors', sa.Column('disabled', sa.Boolean(), nullable=True))
    op.add_column('patients', sa.Column('disabled', sa.Boolean(), nullable=True))
    op.add_column('superusers', sa.Column('disabled', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('superusers', 'disabled')
    op.drop_column('patients', 'disabled')
    op.drop_column('doctors', 'disabled')
    # ### end Alembic commands ###
